# Generated by Django 5.2.6 on 2025-12-04 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'Turi būti bent 5 simboliai'), django.core.validators.MaxLengthValidator(50, 'Turi būti ne daugiau nei 50 simbolių')])),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Admin', 'Administratorius'), ('Registered', 'Registruotas naudotojas'), ('Guest', 'Naudotojas')], max_length=10)),
                ('display_name', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('profile_cover_url', models.ImageField(null=True, upload_to='')),
                ('profile_cover_small_url', models.ImageField(null=True, upload_to='')),
                ('two_factor_enabled', models.BooleanField()),
                ('two_factor_method', models.IntegerField()),
                ('two_factor_secret', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fallowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('A', 'Aktyvus'), ('B', 'Užblokuotas'), ('S', 'Nutildytas')], max_length=1)),
                ('fallowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallowers', to='users.user')),
                ('fallower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallowing', to='users.user')),
            ],
        ),
    ]
