# Generated by Django 5.2.6 on 2025-11-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=50)),
                ('role', models.SmallIntegerField()),
                ('display_name', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('profile_cover_url', models.ImageField(upload_to='')),
                ('profile_cover_small_url', models.ImageField(upload_to='')),
                ('two_factor_enabled', models.BooleanField()),
                ('two_factor_method', models.IntegerField()),
                ('two_factor_secret', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
