# Generated by Django 5.2.6 on 2025-12-07 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_blocked',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(editable=False, max_length=50, validators=[django.core.validators.MinLengthValidator(5, 'Turi būti bent 5 simboliai'), django.core.validators.MaxLengthValidator(50, 'Turi būti ne daugiau nei 50 simbolių')]),
        ),
    ]
