# Generated by Django 5.2.6 on 2025-12-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_factor_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_secret',
        ),
        migrations.CreateModel(
            name='TwoFaSecretCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_created=True, editable=False)),
                ('secret', models.CharField(editable=False, max_length=32)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twoFaSecrets', to='users.user')),
            ],
        ),
    ]
