# Generated by Django 5.2.6 on 2025-11-22 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_myuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('A', 'Aktyvus'), ('B', 'Užblokuotas'), ('S', 'Nutildytas')], max_length=1)),
                ('fallowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sekamasis', to='users.user')),
                ('fallower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sekejas', to='users.user')),
            ],
        ),
    ]
