# Generated by Django 5.2.6 on 2025-12-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_two_factor_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twofasecretcopy',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
