# Generated by Django 5.2.6 on 2025-12-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_active_user_is_blocked_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_cover_small_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_cover_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers'),
        ),
    ]
