# Generated by Django 5.2.6 on 2025-11-22 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fallowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallowing',
            name='fallowed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallowers', to='users.user'),
        ),
        migrations.AlterField(
            model_name='fallowing',
            name='fallower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallowing', to='users.user'),
        ),
    ]
