# Generated by Django 5.2.6 on 2025-12-10 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_twofasecretcopy_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TwoFaCodeCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.BinaryField(max_length=60)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twoFaSecrets', to='users.user')),
            ],
        ),
        migrations.DeleteModel(
            name='TwoFaSecretCopy',
        ),
    ]
