# Generated by Django 5.2.6 on 2025-11-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_fallowing_fallowed_alter_fallowing_fallower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_cover_small_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_cover_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administratorius'), ('Registered', 'Registruotas naudotojas'), ('Guest', 'Naudotojas')], max_length=10),
        ),
    ]
