# Generated by Django 5.2.6 on 2025-12-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_two_factor_secret_twofacodecopy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='state',
            field=models.CharField(choices=[('A', 'Aktyvus'), ('B', 'Užblokuotas'), ('S', 'Nutildytas'), ('N', 'Nieko')], default='N', max_length=1),
        ),
    ]
