# Generated by Django 5.2.6 on 2025-12-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('trukme_sekundes', models.IntegerField()),
                ('zanras', models.CharField(choices=[('popmuzika', 'Pop muzika'), ('rokas', 'Rokas'), ('metalas', 'Metalas'), ('dziasas', 'Dziazas'), ('bliuzas', 'Bliuzas'), ('klasika', 'Klasika'), ('elektronika', 'Elektronika'), ('repas', 'Repas'), ('rnb', 'R&B'), ('kantri', 'Kantri'), ('folk', 'Folk'), ('regis', 'Regis'), ('alternatyva', 'Alternatyva'), ('disco', 'Disco'), ('dance', 'Dance'), ('ambient', 'Ambient'), ('eksperimentine', 'Eksperimentine'), ('instrumentine', 'Instrumentine'), ('opera', 'Opera'), ('pasaulio_muzika', 'Pasaulio muzika'), ('trep', 'Trep'), ('techno', 'Techno'), ('house', 'House')], default='popmuzika', max_length=50)),
                ('isleidimo_data', models.DateField(blank=True, null=True)),
                ('paleidimu_kiekis', models.IntegerField(default=0)),
                ('zodziai', models.TextField(blank=True)),
                ('failas_url', models.TextField()),
                ('virselis_url', models.TextField(blank=True)),
                ('aprasymas', models.TextField(blank=True)),
                ('ikelimo_data', models.DateField(auto_now_add=True)),
                ('yra_viesa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DainosKlausymas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trukme_procentais', models.FloatField()),
                ('klausymo_data', models.DateField(auto_now_add=True)),
                ('daina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klausymai', to='music.daina')),
            ],
        ),
        migrations.CreateModel(
            name='DainosVertinimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivertinimas', models.FloatField()),
                ('ivertinimo_data', models.DateField(auto_now_add=True)),
                ('daina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertinimai', to='music.daina')),
            ],
        ),
    ]
