# Generated by Django 5.2.6 on 2025-12-08 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daina',
            name='savininkas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dainos', to='users.user'),
            preserve_default=False,
        ),
    ]
