# Generated by Django 5.2.6 on 2025-12-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_daina_savininkas'),
        ('users', '0004_user_two_factor_secret_twofacodecopy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dainosklausymas',
            name='naudotojas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='klausymai', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dainosvertinimas',
            name='naudotojas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vertinimai', to='users.user'),
            preserve_default=False,
        ),
    ]
