# Generated by Django 5.2.6 on 2025-12-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_dainosklausymas_naudotojas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dainosvertinimas',
            name='ivertinimo_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
