# Generated by Django 5.2.6 on 2025-12-08 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grojarastis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('aprasymas', models.TextField(blank=True, null=True)),
                ('yra_viesas', models.BooleanField(default=True)),
                ('sukurimo_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('atnaujinimo_data', models.DateTimeField(auto_now=True)),
                ('savininkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grojarasciai', to='users.user')),
            ],
            options={
                'verbose_name': 'Grojarastis',
                'verbose_name_plural': 'Grojarasčiai',
                'ordering': ['-sukurimo_data'],
            },
        ),
        migrations.CreateModel(
            name='GrojarascioVertinimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ivertinimas', models.FloatField()),
                ('ivertinimo_data', models.DateTimeField(auto_now_add=True)),
                ('naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grojarasciu_vertinimai', to='users.user')),
                ('grojarastis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertinimai', to='playlists.grojarastis')),
            ],
            options={
                'verbose_name': 'GrojarascioVertinimas',
                'verbose_name_plural': 'GrojarasčioVertinimai',
                'unique_together': {('grojarastis', 'naudotojas')},
            },
        ),
        migrations.CreateModel(
            name='GrojarastisDaina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prideta_data', models.DateField(auto_created=True)),
                ('eilės_nr', models.PositiveIntegerField(default=0)),
                ('daina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grojarasciai', to='music.daina')),
                ('grojarastis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dainos', to='playlists.grojarastis')),
            ],
            options={
                'verbose_name': 'GrojarastisDaina',
                'verbose_name_plural': 'GrojarasčioDainos',
                'ordering': ['eilės_nr'],
                'unique_together': {('grojarastis', 'daina')},
            },
        ),
    ]
