# Generated by Django 5.2.6 on 2025-12-13 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_daina_savininkas'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grojarastisdaina',
            options={'ordering': ['eiles_nr']},
        ),
        migrations.AlterUniqueTogether(
            name='grojarastisdaina',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grojarastisdaina',
            name='daina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='music.daina'),
        ),
        migrations.AlterField(
            model_name='grojarastisdaina',
            name='eiles_nr',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='grojarastisdaina',
            name='prideta_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='grojarastisdaina',
            unique_together={('grojarastis', 'eiles_nr')},
        ),
    ]
