# Generated by Django 5.2.6 on 2025-12-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grojarastisdaina',
            unique_together={('grojarastis', 'eilės_nr')},
        ),
        migrations.AddField(
            model_name='grojarastisdaina',
            name='atlikėjo_vardas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='grojarastisdaina',
            name='dainos_pavadinimas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='grojarastisdaina',
            name='daina',
        ),
        migrations.RemoveField(
            model_name='grojarastisdaina',
            name='prideta_data',
        ),
    ]
