# Generated by Django 5.2.6 on 2025-12-04 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.TextField()),
                ('adresas', models.TextField()),
                ('miestas', models.TextField()),
                ('salis', models.TextField()),
                ('platuma', models.FloatField(default=0)),
                ('ilguma', models.FloatField(default=0)),
                ('laiko_zona', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Koncertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.TextField()),
                ('pradzios_data', models.DateField(blank=True, null=True)),
                ('pabaigos_data', models.DateField(blank=True, null=True)),
                ('bilietu_url', models.TextField()),
                ('aprasymas', models.TextField()),
                ('sukurimo_data', models.DateField(blank=True, null=True)),
                ('atnaujinimo_data', models.DateField(blank=True, null=True)),
                ('yra_atsauktas', models.BooleanField(default=False)),
                ('zmoniu_talpa', models.IntegerField()),
                ('zanras', models.CharField(choices=[('popmuzika', 'Pop muzika'), ('rokas', 'Rokas'), ('metalas', 'Metalas'), ('dziasas', 'Džiazas'), ('bliuzas', 'Bliuzas'), ('klasika', 'Klasika'), ('elektronika', 'Elektronika'), ('repas', 'Repas'), ('rnb', 'R&B'), ('kantri', 'Kantri'), ('folk', 'Folk'), ('regis', 'Regis'), ('alternatyva', 'Alternatyva'), ('disco', 'Disco'), ('dance', 'Dance'), ('ambient', 'Ambient'), ('eksperimentine', 'Eksperimentinė'), ('instrumentine', 'Instrumentinė'), ('opera', 'Opera'), ('pasaulio_muzika', 'Pasaulio muzika'), ('trep', 'Trep'), ('techno', 'Techno'), ('house', 'House')], default='popmuzika', max_length=255)),
                ('yra_viesas', models.BooleanField(default=True)),
                ('rekomendacijos_ivertis', models.FloatField(default=0)),
                ('vieta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koncertai', to='concerts.vieta')),
            ],
        ),
        migrations.CreateModel(
            name='KoncertoDalyvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dalyvavimo_busena', models.CharField(choices=[('dalyvauja', 'Dalyvauja'), ('domina', 'Domina'), ('isaugota', 'Isaugota')], default='domina', max_length=50)),
                ('koncertas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dalyviai', to='concerts.koncertas')),
                ('vartotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koncertu_dalyviai', to='users.user')),
            ],
            options={
                'unique_together': {('vartotojas', 'koncertas')},
            },
        ),
    ]
