# Generated by Django 6.0 on 2025-12-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='koncertas',
            name='rekomendacijos_ivertis',
        ),
    ]
