# Generated by Django 5.2.6 on 2025-10-26 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='concert',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='date',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='price',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='title',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='venue',
        ),
        migrations.AddField(
            model_name='concert',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Concert end date and time'),
        ),
        migrations.AddField(
            model_name='concert',
            name='genre',
            field=models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('hip_hop', 'Hip Hop'), ('country', 'Country'), ('blues', 'Blues'), ('folk', 'Folk'), ('metal', 'Metal'), ('reggae', 'Reggae'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='concert',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Is the concert cancelled?'),
        ),
        migrations.AddField(
            model_name='concert',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Is the concert visible to public?'),
        ),
        migrations.AddField(
            model_name='concert',
            name='name',
            field=models.CharField(default='Untitled Concert', help_text='Concert name', max_length=200),
        ),
        migrations.AddField(
            model_name='concert',
            name='recommendation_score',
            field=models.FloatField(default=0.0, help_text='Recommendation score (0.0 to 10.0)'),
        ),
        migrations.AddField(
            model_name='concert',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Concert start date and time'),
        ),
        migrations.AddField(
            model_name='concert',
            name='ticket_number',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of tickets available'),
        ),
        migrations.AddField(
            model_name='concert',
            name='ticket_url',
            field=models.URLField(blank=True, help_text='URL to purchase tickets', null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=models.TextField(blank=True, help_text='Concert description'),
        ),
    ]
