# Generated by Django 5.2.6 on 2025-11-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_options_remove_concert_artist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concert',
        ),
    ]
